version: '3'
services:
  app:
    build:
      context: .
    image: node
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - .:/src
    command: [sh, -c, npm install && npm start]
