version: '3'
services:
  app:
    build:
      context: .
    image: node
    container_name: node
    tty: true
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - .:/src
    command: [sh, -c, npm install && npm start]
    depends_on:
      - db

  db:
    image: postgres:13.5
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}

